### PR TITLE
Added skipper-azure adapter.

### PR DESCRIPTION
**Pull request by lukasreichart**
I just wrote and published a skipper adapter for the Microsoft Azure cloud storage.

### CODE REVIEW

**Comment by lukasreichart** [comment]
@mikermcneil

**Comment by matiaslarsson** [comment]
Nice work @lukasreichart! Using it as we speak! :)

**Comment by lukasreichart** [comment]
@matiaslarsson thanks :D

**Comment by tjwebb** [comment]
@lukasreichart thanks!

**Pull request merged**
