### PR TITLE
cloneDeep breaks stuff. stop using it.

### PR DESCRIPTION
**Pull request by tjwebb**
also rename `____` variables

### CODE REVIEW

**Comment by Alaneor** [comment]
Actually it does break stuff. :) I was about to send a pull request to remove the offending line when I noticed this PR was merged and then reverted.

**My use case:**

I am implementing a Skipper adapter as a ES 2015 class. The problem is that `_.deepClone()` creates a copy of my `adapter` object instead of passing along the actual class instance. This results in the instance methods being undefined (because prototype properties are not copied over) and it also causes secondary issues with `this` being suddenly a different object in the methods.

Consider:

```js
req.file('file').upload(
  { adapter: require('my-adapter')
  // other options as necessary
  }
, (err, files) => done(err, files))
```

Where the required adapter object is basically the result of calling `new Adapter()` (Adapter being a class).

I assume the PR was reverted for a good reason, but... If completely omitting the cloning is not an option, can we at least keep the `adapter` property intact? The following example works for my use case just as well:

```js
var receiverOpts = _.cloneDeep(opts);

if (opts.adapter instanceof Object) {
  receiverOpts.adapter = opts.adapter;
}
```

It this would be acceptable I can have a PR ready in no time.

**Comment by tjwebb** [comment]
Where was this reverted?

**Comment by Alaneor** [comment]
Reverted in 7474803265196b7e0d296c62d416bdd40a5181eb by @mikermcneil.

Unfortunately there is no information in the commit as to why a revert was necessary, so I can only assume it broke something somewhere...

**Comment by tjwebb** [comment]
@mikermcneil why did you revert this? This was causing insidious and inexplicable errors, which is why I changed it. If it broke something, let's come up with a plan to figure that out. Silently reverting a valid PR is not helpful

**Comment by RWOverdijk** [comment]
:+1:

**Comment by mikermcneil** [comment]
@tjwebb I wasn't able to determine what this PR was really for, and since I couldn't trace down any reason to merge this, I reverted it.  Additionally, this PR made code style changes that violate the going forward approach used by the Sails and Express teams (e.g. `/** Module dependencies */`)

> insidious and inexplicable errors
I definitely don't want anyone to have to deal with those-- but I need more details than that before this can be merged.  Without `_.cloneDeep()`, it is very easy to accidentally modify properties on a dictionary which is used internally by Skipper core.  Cloning also prevents against Skipper inadvertently modifying properties on the adapter object.

> I am implementing a Skipper adapter as a ES 2015 class.
@Alaneor This clone is part of the private internal API of Skipper. Skipper supports adapters defined as traditional JavaScript objects; no prototypal props, methods, etc.  There's nothing wrong with higher-level coding styles, but the documented usage of Skipper shows using a normal JavaScript object (aka dictionary), and that's the approach we're going to stick with. if you can normalize your adapter into a plain JavaScript dictionary, everything should work.

Sorry to hard line on this, but this is the type of change for the purpose of aesthetics that I have learned to avoid with open source over the years.  It ends up being better for all of us.

If anyone comes across problems caused by this when using Skipper when using the official documented usage, please let me know.  Thanks guys.

**Comment by Alaneor** [comment]
Thanks for the explanation. It's unfortunate, but yes - I ended up exporting a wrapper object for the instance which solves this for me.

**Comment by tjwebb** [comment]
>  I wasn't able to determine what this PR was really for, and since I couldn't trace down any reason to merge this, I reverted it
> Without _.cloneDeep(), it is very easy to accidentally modify properties 

`_.cloneDeep` needs to stop being used as panacea for all sorts of potential and imaginary problems. It's the reason we can't upgrade to lodash 3.x, and is **causing** many more problems than it's solving. 

Reverting this PR accomplished little more than causing 3 people to complain in this thread about it being reverted. I'm going to submit another PR, because it's solving a problem that needs to be solved.

**Pull request merged**
