### PR TITLE
Handle multiple error events on the incoming _filestream (Issue #74)

### PR DESCRIPTION
**Pull request by nitzo**
Event handler is now registered more than once but does cleanup only once. This prevents server crash if an error is emitted twice on the stream.  See issue #74

### CODE REVIEW

**Comment by tjwebb** [comment]
Does this resolve #49?

**Comment by nitzo** [comment]
Yes this resolves #49 and #74

**Comment by nitzo** [comment]
Any chance this could be merged soon ?

Thanks!

**Comment by tjwebb** [comment]
Yes, sorry for the delay in reviewing it. Is it possible to include a simple test so we'll be able to test for regressions in this issue?

**Comment by tjwebb** [comment]
@nitzo ^^

**Comment by nitzo** [comment]
Hi @tjwebb sorry about the delay.
I'll just make sure I understand you - 
You want me to add a new test case to the project's tests ? Or just provide a test example for you to review?

Thanks!

**Comment by tjwebb** [comment]
Yea, is it possible to include a test that fails on the current version of skipper, and passes on this PR which includes your fix? That'll help document what the issue was, how it was fixed, etc. Thanks!

**Comment by mahasen** [comment]
@nitzo I tried your snippet of code (https://github.com/nitzo/skipper/commit/b7cb9fb04ee0a5c9fd8fcb2f43d2ba1b15419dc4) with no luck :(

Sails crashes with the following error:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Request aborted
    at IncomingMessage.onReqAborted ({path}/node_modules/sails/node_modules/skipper/node_modules/multiparty/index.js:175:17)
    at IncomingMessage.emit (events.js:104:17)
    at abortIncoming (_http_server.js:279:11)
    at Socket.socketOnEnd (_http_server.js:393:7)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

Using: sails 0.11.1, skipper-s3 0.5.5, node 0.12.5

**Comment by nitzo** [comment]
@mahasen Can you post the code that handles the upload ? This fix worked for me and solved my issue...

**Comment by mahasen** [comment]
@nitzo thanks for getting back. I replaced this section of `skipper/standalone/Upstream/prototype.writeFile.js`:

```javascript
    var leaky = new Writable();
    leaky._write = function(chunk, encoding, cb) {
      cb();
    };
    __filestream.unpipe();
    __filestream.pipe(leaky);
    log('Piping the not-yet-written bytes from incoming file `' + __filestream.filename + '` to the memory hole..');
```
**with this**

```javascript
    var hasFired = false;

    return function(err) {
          
        if (!hasFired) {
            var leaky = new Writable();
            leaky._write = function(chunk, encoding, cb) {
                cb();
            };
            __filestream.unpipe();
            __filestream.pipe(leaky);
            log('Piping the not-yet-written bytes from incoming file `' + __filestream.filename + '` to the memory hole..');
        }

        hasFired = true;
    };
```

**Comment by oneHappyCanuck** [comment]
Also waiting on this merge, we have an app going into production shortly.  Thx,

**Comment by tjwebb** [comment]
@oneHappyCanuck I'm waiting on unit tests for this PR. Some people have noted that this fix breaks other things.

**Comment by devyn** [comment]
+1, my app currently crashes on every upload because of this

**Comment by nitzo** [comment]
Hi,

I did not have the time to write unit tests yet. My application is running in production with no issues with this fix. @devyn if you could submit the code you are using to upload the files (Your controller code) that could be great.

Tnx

**Pull request merged**
