### PR TITLE
acceptFile implementation

### PR DESCRIPTION
**Pull request by jurajpetrik**
I've taken a shot at implementing the acceptFile function as discussed in the https://github.com/balderdashy/skipper/blob/master/ROADMAP.md

### CODE REVIEW

**Comment by tjwebb** [comment]
@mikermcneil can you review this?

**Comment by jurajpetrik** [comment]
Any feedback on this? It was mentioned in a lot of issues.. https://github.com/balderdashy/skipper/issues/54
https://github.com/balderdashy/skipper/issues/35

**Comment by tjwebb** [comment]
@sgress454 @mikermcneil ^^

**Comment by mikermcneil** [comment]
@jurajpetrik Thanks!  And sorry about the slow turnaround.  Reviewing now.

**Comment by mikermcneil** [comment]
@jurajpetrik would you mind sending this PR again without all the whitespace changes?  Thanks!

**Comment by elennaro** [comment]
When do you plan to merge this?

**Comment by mikermcneil** [comment]
> When do you plan to merge this?

@elennaro see https://github.com/balderdashy/skipper/pull/81#issuecomment-141573527

**Comment by mikermcneil** [comment]
^ also, while @jurajpetrik did a great job updating the docs in the README, this PR will also need some accompanying tests before we can get it merged.  @elennaro if this is something you have a use case for, we'd welcome your help.  Thanks!

**Comment by jurajpetrik** [comment]
@mikermcneil @elennaro I'm not using sails or skipper anymore so I don't have time to follow through with this PR. It's been almost a year since I made it and I barely remember what it contains anymore. You are welcome to take and change it to fit your needs.

**Comment by elennaro** [comment]
@mikermcneil I gave up using **skipper** and switched to busboy.
But if it is ok to you, I can try to write some tests for this PR and remove whitespace changes. A little bit later when I have a free weekend at least.

**Comment by elennaro** [comment]
Sorry I can't write the test for the PR now... It does not do exactly what I expected. 

And during writing the test I discovered that `fileMetadata.size` and `fileMetadata.type` are sometimes `undefined`.
So implementation should be rechecked and I don't have time for this now.
Sorry.

**Comment by mikermcneil** [comment]
@jurajpetrik @elennaro Hi guys, thanks again for taking the time to take a pass at this.  It sounds like no one is working on this at the moment, but I'll leave it open in case anyone would like to take over and finish up the `acceptFile` implementation.  Neither @sgress454 nor I will have time to work on this in the next month or so, but after that, we'll be able to help out if you need questions answered, etc.

**Comment by DeVoresyah** [comment]
it has been 4 years, and still need it. Any updates?

**Comment by jurajpetrik** [comment]
It's been years since I even touched Sails. Feel free to use this code as you wish but I won't be doing any more work on it.

**Pull request closed without merging**
