### PR TITLE
Fixing what appears to be a bug

### PR DESCRIPTION
**Pull request by schematical**
I am not sure if they ever could allow you to pass the `maxTimeToBuffer` option in but it doesn't look like it. I just modded it so you could and added a quick bit of documentation.

### CODE REVIEW

**Comment by mikermcneil** [comment]
@schematical this looks great!  Would you mind adding a test that fails without this patch?

**Comment by schematical** [comment]
@mikermcneil Not sure where the best spot to put that would be. Obviously in https://github.com/balderdashy/skipper/blob/master/test/ but any specific set of tests or create a new test for it?

**Comment by mikermcneil** [comment]
@schematical I'd say make a new test file named `timeouts.test.js` and do something along the lines of [this test](https://github.com/balderdashy/skipper/blob/master/test/req.file.upload.test.js), except setting up a couple of different scenarios:  one where you deliberately pass in a very small `maxTimeToBuffer` and the other where you pass in a very small `maxTimeToWaitForFirstFile`.  If you could get those two tests failing without your patch, then add the patch to prove that they work, I'll merge this asap and we can republish.  Thanks!

**Comment by okankurtulus** [comment]
Hi, is there any progress on merging the pull request?

**Comment by mikermcneil** [comment]
@okankurtulus Thanks for the ping.  We're just getting time to get into it- I believe @sgress454 is looking at this and the other related Skipper patch this week.

**Comment by sgress454** [comment]
Thanks @schematical!

**Pull request merged**
